version: '3.8'

services:
  eye-tracking-backend:
    build:
      context: .
      dockerfile: Dockerfile.production
    ports:
      - "${EXTERNAL_PORT:-5000}:5000"
    environment:
      - HOST=0.0.0.0
      - PORT=5000
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - MAX_CONNECTIONS=${MAX_CONNECTIONS:-100}
      - PING_INTERVAL=${PING_INTERVAL:-20}
      - PING_TIMEOUT=${PING_TIMEOUT:-20}
    restart: unless-stopped
    networks:
      - eye-tracking-network
    # Resource limits for production
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 256M
    # Security options
    security_opt:
      - no-new-privileges:true
    # Read-only root filesystem for security
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid,size=100m
    # Health check
    healthcheck:
      test: ["CMD", "python", "health_check.py"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Nginx reverse proxy
  nginx:
    image: nginx:alpine
    ports:
      - "${NGINX_PORT:-80}:80"
      - "${NGINX_SSL_PORT:-443}:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro  # SSL certificates
    depends_on:
      - eye-tracking-backend
    restart: unless-stopped
    networks:
      - eye-tracking-network

networks:
  eye-tracking-network:
    driver: bridge
