version: '3.8'

services:
  eye-tracking-backend:
    build:
      context: .
      dockerfile: Dockerfile.simple
    ports:
      - "5000:5000"
    environment:
      - HOST=0.0.0.0
      - PORT=5000
    volumes:
      # Mount the current directory for development
      - .:/app
    restart: unless-stopped
    # For development, you might want to enable camera access
    # devices:
    #   - "/dev/video0:/dev/video0" 